### ISSUE TITLE
[Build Failure] Plugin fails to build in CI

### ISSUE THREAD

**Issue by robbavey** [logstash-plugins/logstash-output-google_bigquery#66]
https://app.travis-ci.com/github/logstash-plugins/logstash-output-google_bigquery/jobs/547075212

```
Resolving dependencies.....................................
Fetching rake 13.0.6
Installing rake 13.0.6
Fetching public_suffix 4.0.7
Installing public_suffix 4.0.7
Fetching addressable 2.8.0
Installing addressable 2.8.0
Using bundler 1.17.3
Fetching clamp 1.3.2
Installing clamp 1.3.2
Fetching coderay 1.1.3
Installing coderay 1.1.3
Fetching concurrent-ruby 1.1.10
Installing concurrent-ruby 1.1.10
Fetching diff-lcs 1.5.0
Installing diff-lcs 1.5.0
Fetching down 5.2.4
Installing down 5.2.4
Fetching multi_json 1.15.0
Installing multi_json 1.15.0
Fetching elasticsearch-api 7.17.1
Installing elasticsearch-api 7.17.1
Fetching faraday-em_http 1.0.0
Installing faraday-em_http 1.0.0
Fetching faraday-em_synchrony 1.0.0
Installing faraday-em_synchrony 1.0.0
Fetching faraday-excon 1.1.0
Installing faraday-excon 1.1.0
Fetching faraday-httpclient 1.0.1
Installing faraday-httpclient 1.0.1
Fetching multipart-post 2.2.0
Installing multipart-post 2.2.0
Fetching faraday-multipart 1.0.4
Installing faraday-multipart 1.0.4
Fetching faraday-net_http 1.0.1
Installing faraday-net_http 1.0.1
Fetching faraday-net_http_persistent 1.2.0
Installing faraday-net_http_persistent 1.2.0
Fetching faraday-patron 1.0.0
Installing faraday-patron 1.0.0
Fetching faraday-rack 1.0.0
Installing faraday-rack 1.0.0
Fetching faraday-retry 1.0.3
Installing faraday-retry 1.0.3
Fetching ruby2_keywords 0.0.5
Installing ruby2_keywords 0.0.5
Fetching faraday 1.10.0
Installing faraday 1.10.0
Fetching elasticsearch-transport 7.17.1
Installing elasticsearch-transport 7.17.1
Fetching elasticsearch 7.17.1
Installing elasticsearch 7.17.1
Fetching tzinfo 2.0.4
Installing tzinfo 2.0.4
Fetching et-orbi 1.2.7
Installing et-orbi 1.2.7
Fetching ffi 1.15.5 (java)
Installing ffi 1.15.5 (java)
Fetching filesize 0.2.0
Installing filesize 0.2.0
Fetching fivemat 1.3.7
Installing fivemat 1.3.7
Fetching raabro 1.4.0
Installing raabro 1.4.0
Fetching fugit 1.5.3
Installing fugit 1.5.3
Fetching gem_publisher 1.5.0
Installing gem_publisher 1.5.0
Fetching gems 1.2.0
Installing gems 1.2.0
Fetching i18n 1.10.0
Installing i18n 1.10.0
Fetching jar-dependencies 0.3.12
Installing jar-dependencies 0.3.12
Fetching jrjackson 0.4.14 (java)
Installing jrjackson 0.4.14 (java)
Fetching jruby-openssl 0.13.0 (java)
Installing jruby-openssl 0.13.0 (java)
Fetching kramdown 1.14.0
Installing kramdown 1.14.0
Fetching openssl_pkcs8_pure 0.0.0.2
Installing openssl_pkcs8_pure 0.0.0.2
Fetching manticore 0.9.0 (java)
Installing manticore 0.9.0 (java)
Fetching minitar 0.9
Installing minitar 0.9
Fetching mustermann 1.0.3
Installing mustermann 1.0.3
Fetching method_source 1.0.0
Installing method_source 1.0.0
Fetching spoon 0.0.6
Installing spoon 0.0.6
Fetching pry 0.14.1 (java)
Installing pry 0.14.1 (java)
Fetching nio4r 2.5.8 (java)
Installing nio4r 2.5.8 (java)
Fetching puma 5.6.4 (java)
Installing puma 5.6.4 (java)
Using racc 1.5.2 (java)
Fetching rack 2.2.3.1
Installing rack 2.2.3.1
Fetching rubyzip 1.3.0
Installing rubyzip 1.3.0
Fetching rufus-scheduler 3.8.1
Installing rufus-scheduler 3.8.1
Fetching rack-protection 2.2.0
Installing rack-protection 2.2.0
Fetching tilt 2.0.10
Installing tilt 2.0.10
Fetching sinatra 2.2.0
Installing sinatra 2.2.0
Fetching stud 0.0.23
Installing stud 0.0.23
Fetching thread_safe 0.3.6 (java)
Installing thread_safe 0.3.6 (java)
Fetching polyglot 0.3.5
Installing polyglot 0.3.5
Fetching treetop 1.6.11
Installing treetop 1.6.11
Fetching tzinfo-data 1.2022.1
Installing tzinfo-data 1.2022.1
Using logstash-core 8.0.0 (java) from source at `../../logstash/logstash-core`
Using logstash-core-plugin-api 2.1.16 (java) from source at `../../logstash/logstash-core-plugin-api`
Fetching logstash-mixin-ecs_compatibility_support 1.3.0 (java)
Installing logstash-mixin-ecs_compatibility_support 1.3.0 (java)
Fetching logstash-mixin-event_support 1.0.1 (java)
Installing logstash-mixin-event_support 1.0.1 (java)
Fetching logstash-codec-plain 3.1.0
Installing logstash-codec-plain 3.1.0
Fetching rspec-support 3.11.0
Installing rspec-support 3.11.0
Fetching rspec-core 3.11.0
Installing rspec-core 3.11.0
Fetching rspec-expectations 3.11.0
Installing rspec-expectations 3.11.0
Fetching rspec-mocks 3.11.1
Installing rspec-mocks 3.11.1
Fetching rspec 3.11.0
Installing rspec 3.11.0
Fetching rspec-wait 0.0.9
Installing rspec-wait 0.0.9
Fetching logstash-devutils 2.4.0 (java)
Installing logstash-devutils 2.4.0 (java)
Fetching mime-types 2.99.3
Installing mime-types 2.99.3
Using logstash-output-google_bigquery 4.1.5 (java) from source at `.`
Bundle complete! 5 Gemfile dependencies, 75 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Post-install message from jar-dependencies:
if you want to use the executable lock_jars then install ruby-maven gem before using lock_jars
  $ gem install ruby-maven -v '~> 3.3.11'
or add it as a development dependency to your Gemfile
   gem 'ruby-maven', '~> 3.3.11'
Post-install message from minitar:
The `minitar` executable is no longer bundled with `minitar`. If you are
expecting this executable, make sure you also install `minitar-cli`.
Removing intermediate container 4d027be95ea0
 ---> e12928935378
Step 22/23 : COPY --chown=logstash:logstash . /usr/share/plugins/plugin/
 ---> e7c172fc0c0c
Step 23/23 : RUN bundle exec rake vendor
 ---> Running in dedbb38cf70b
bundler: failed to load command: rake (/usr/share/logstash/vendor/jruby/bin/rake)
Gem::LoadError: You have already activated jar-dependencies 0.4.1, but your Gemfile requires jar-dependencies 0.3.12. Since jar-dependencies is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports jar-dependencies as a default gem.
  /usr/share/logstash/vendor/jruby/lib/ruby/gems/shared/gems/bundler-1.17.3/lib/bundler/runtime.rb:319:in `check_for_activated_spec!'
  /usr/share/logstash/vendor/jruby/lib/ruby/gems/shared/gems/bundler-1.17.3/lib/bundler/runtime.rb:31:in `block in setup'
  org/jruby/RubyArray.java:1821:in `each'
  org/jruby/RubyEnumerable.java:886:in `map'
  /usr/share/logstash/vendor/jruby/lib/ruby/gems/shared/gems/bundler-1.17.3/lib/bundler/runtime.rb:26:in `setup'
  /usr/share/logstash/vendor/jruby/lib/ruby/gems/shared/gems/bundler-1.17.3/lib/bundler.rb:107:in `setup'
  /usr/share/logstash/vendor/jruby/lib/ruby/gems/shared/gems/bundler-1.17.3/lib/bundler/setup.rb:20:in `<main>'
  org/jruby/RubyKernel.java:974:in `require'
  /usr/share/logstash/vendor/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:83:in `require'
ERROR: Service 'logstash' failed to build: The command '/bin/sh -c bundle exec rake vendor' returned a non-zero code: 1
The command ".ci/docker-setup.sh" failed and exited with 1 during .
```

**Comment by robbavey** [comment]
Closing - builds successfully https://app.travis-ci.com/github/logstash-plugins/logstash-output-google_bigquery/builds/273408881
